// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtkajnyffgefhiogrfri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0a2FqbnlmZmdlZmhpb2dyZnJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NDY5OTIsImV4cCI6MjA2NDIyMjk5Mn0.zSPqj17-JDXjRUvSAQeWkwU-A8zIj7qcP6Q5vpJEr-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);